/**

Provides classes for compiling formulas from strings. The lexer and parser are
generated by <a href="http://www.antlr.org">ANTLR</A> from an EBNF grammar.
Essa package foi criado apenas para separar a gramatica relativa a Macro da gramatica da Formula. 

*/
package csheets.ext.editMacro.compiler;